# Generated by Django 4.2.6 on 2023-11-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_employer_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='is_approved',
        ),
    ]
