# Generated by Django 4.2.6 on 2023-11-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_employee_is_approved_employer_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='is_approved',
        ),
    ]
