# Generated by Django 4.2.6 on 2023-12-09 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_employee_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AddField(
            model_name='profile',
            name='employer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employer'),
        ),
    ]
