# Generated by Django 4.2.6 on 2023-12-09 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_employee_profile_employer'),
    ]

    operations = [
    ]
