# Generated by Django 4.2.6 on 2023-10-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0003_alter_job_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='date_added',
            new_name='date_posted',
        ),
    ]
